### ISSUE TITLE
add to gotchas

### ISSUE THREAD

**Issue by sdchasalow** [maptracker/GeneralUtility#1]
1.  table(x, exclude = NULL) if you don't want to ignore NAs
2.  sample(x) usually does not do what you expect if length(x) == 1 !!  See ?sample (esp. Examples).
3.  ggplot( mydata[order(mydata$C), ], aes(x = mydata$A, y = mydata$B)) does REALLY WAY bad stuff if you subset or reorder mydata.  Use aes(x = A, y = B) instead. Via @rossmacp
4.  Use seq_len(length(x)), never 1:length(x), in case length(x) == 0

**Comment by sdchasalow** [comment]
How wonderfully insightful!

**Comment by maptracker** [comment]
Added to [GotchasInR.md](https://github.com/maptracker/GeneralUtility/blob/master/GotchasInR.md)

**Comment by maptracker** [comment]
Testing mentions: @sdchasalow
